baseURL = "https://hugoprudente.github.io"

googleAnalytics = "UA-154006380-1"
theme = "hello-friend-ng"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
disqusShortname = "hugoprudente"


[author]
  name = "Hugo Prudente"

[taxonomies]
  tag      = "tags"
  category = "categories"

[languages]
[languages.en]
weight = 0
title  = "Hugo Prudente"

  [[languages.en.menu.main]]
  url = "/posts"
  name = "Blog"
  weight = 0
  
  [languages.en.params.logo]
  logoText = "make"
  logoHomeLink = "/en/"

[languages.pt-br]
weight = 1
title  = "Hugo Prudente"

  [[languages.pt-br.menu.main]]
  url = "/pt-br/posts"
  name = "Blog"
  weight = 0
  
  [languages.pt-br.params.logo]
  logoText = "make"
  logoHomeLink = "/pt-br/"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02T05:04-0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Automation above all things"
  subtitle = "devops"
  keywords = "posts, programming, devops, sysadmin, security, automation, aws"
  images = [""]

  # Directory name of your posts content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  homeSubtitle = "Automation above all things"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/hugoprudente"

  [[params.social]]
    name = "github"
    url  = "https://github.com/hugoprudente"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/1463918/hugo-prudente"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/hugoprudente/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
